name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: sudo -E `which cargo` test -j`nproc` -- --test-threads 1
      - run: sudo -E `which cargo` test -j`nproc` -- --ignored --test-threads 1
      - run: sudo -E `which cargo` fmt -- --check
      - run: sudo -E `which cargo` clippy -j`nproc`
