name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: sudo -E `which cargo` test -- --test-threads 1
      - run: sudo -E `which cargo` test -- --ignored --test-threads 1
      - run: sudo -E `which cargo` fmt -- --check
